TRAIN:
  ENABLE: True
  BATCH_SIZE: 64
  DATASET: Cars
  CHECKPOINT_DIR: checkpoints/ProTrans/cars/15
DATA:
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  SAMPLING_RATES: 0.15
MODEL:
  NUM_CLASSES: 196
  ARCH: resnet50
  ARCH_PRETRAINED: True
  FC:
    BIAS: False
SOLVER:
  OPTIMIZING_METHOD: sgd
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  NESTEROV: True
  BASE_LR: 0.001
  LR_POLICY: cosine
  COSINE_END_LR: 0.0
  COSINE_AFTER_WARMUP: False
  WARMUP_EPOCHS: 0
PROTRANS:
  ENABLE: True
  LAMBDA_AGGR: 25.0
  LAMBDA_SEP: 3.0
RESULT_DIR: results/ProTrans/cars/15
NUM_GPUS: 1