TRAIN:
  ENABLE: True
  BATCH_SIZE: 64
  DATASET: CUB200
  CHECKPOINT_DIR: checkpoints/CE/cub200/15
DATA:
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  SAMPLING_RATES: 0.15
MODEL:
  NUM_CLASSES: 200
  ARCH: resnet50
  ARCH_PRETRAINED: True
SOLVER:
  OPTIMIZING_METHOD: sgd
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  NESTEROV: True
  BASE_LR: 0.001
  LR_POLICY: cosine
  COSINE_END_LR: 0.0
  COSINE_AFTER_WARMUP: False
  WARMUP_EPOCHS: 0
RESULT_DIR: results/CE/cub200/15
NUM_GPUS: 1